{
    'name': 'Modulo Prova',
    'version': '16.0.1.0.0',
    'summary': 'Base module template for Odoo 16',
    'description': '',
    'author': 'QuickStart²',
    'website': 'https://www.quickstart2.com',
    'category': 'Uncategorized',
    'depends': [],
    'data': [],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}
